"""Add month, year, hostel_food_fee, milk_fee to fee

Revision ID: 693a9a33e336
Revises: d6bd1d43e91c
Create Date: 2025-10-28 00:14:55.461537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693a9a33e336'
down_revision = 'd6bd1d43e91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('month', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('fee', sa.Column('year', sa.String(length=10), nullable=False, server_default=''))
    op.add_column('fee', sa.Column('hostel_food_fee', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('fee', sa.Column('milk_fee', sa.Float(), nullable=False, server_default='0.0'))
    op.drop_column('fee', 'food_fee')
    op.drop_column('fee', 'hostel_fee')
    op.drop_column('fee', 'academic_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee', sa.Column('academic_year', sa.VARCHAR(length=10), nullable=False))
    op.add_column('fee', sa.Column('hostel_fee', sa.FLOAT(), nullable=True))
    op.add_column('fee', sa.Column('food_fee', sa.FLOAT(), nullable=True))
    op.drop_column('fee', 'milk_fee')
    op.drop_column('fee', 'hostel_food_fee')
    op.drop_column('fee', 'year')
    op.drop_column('fee', 'month')
    # ### end Alembic commands ###
