"""Add hostel_food_opted and milk_opted to student

Revision ID: d6bd1d43e91c
Revises: 
Create Date: 2025-10-28 00:12:13.061738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bd1d43e91c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('hostel_food_opted', sa.Boolean(), nullable=True))
    op.add_column('student', sa.Column('milk_opted', sa.Boolean(), nullable=True))
    op.drop_column('student', 'hostel_opted')
    op.drop_column('student', 'food_opted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('food_opted', sa.BOOLEAN(), nullable=True))
    op.add_column('student', sa.Column('hostel_opted', sa.BOOLEAN(), nullable=True))
    op.drop_column('student', 'milk_opted')
    op.drop_column('student', 'hostel_food_opted')
    # ### end Alembic commands ###
