"""Add payment_method and transaction_id to PaymentHistory

Revision ID: fd17166ef97d
Revises: 693a9a33e336
Create Date: 2025-10-28 00:27:02.860249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd17166ef97d'
down_revision = '693a9a33e336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_history', sa.Column('payment_method', sa.String(length=10), nullable=True))
    op.add_column('payment_history', sa.Column('transaction_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_history', 'transaction_id')
    op.drop_column('payment_history', 'payment_method')
    # ### end Alembic commands ###
